# Generated by Django 3.2.19 on 2023-05-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image_data', models.TextField()),
                ('description', models.TextField()),
                ('discount', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productss', to='Ecommerce.customers')),
                ('products_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_productss', to='Ecommerce.user')),
            ],
        ),
    ]
